version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - 5500:5500
    environment:
      - ENV=prod
      - MONGODB_URL=${MONGODB_URL} # If running on localhost using docker change it to mongodb://mongodb:27017
    depends_on:
      - mongodb
  client:
    build: ./frontend
    ports:
      - 8011:8011
    environment:
      - ENV=prod
    depends_on:
      - backend